   name: Build and Scan for Vulnerabilities
 
   on:
        push:
          branches: [main]
        pull_request:
          branches: [main]

   jobs:
      build:
          runs-on: ubuntu-latest
          steps:
          - name: Checkout repo
            uses: actions/checkout@v3

          - name: Setup Python Version
            uses: actions/setup-python@v2
            with:
                python-version: 3.9
          
          - name: Setup Ruby Version
            uses: ruby/setup-ruby@v1
            with:
                ruby-version: '2.7'

          - name: Setup node for the whole package
            uses: actions/setup-node@v3

          - name: Clone automated security helper
            uses: actions/checkout@v2
            with:
                repository: aws-samples/automated-security-helper 
                path: ./
          
          - name: Run automated security helper
            run: | 
                ash ..

          - name: Create Scout Suite Report
            uses: actions/upload-artifact@v3
            with:
                name: automated-security-helper-report
                path: aggregated_results.txt
          
          - name: Npm install root directory
            run: npm install
            
          - name: Npm audit root directory
            run:  npm audit

          - name: Install Poetry Action
            uses: snok/install-poetry@v1
            with:
                version: 1.1.13
                virtualenvs-create: true
                virtualenvs-in-project: true
                virtualenvs-path: backend/.venv
                installer-parallel: true
          
          - name: Run yarn install web directory
            uses: Borales/actions-yarn@v4.2.0
            with:
                dir: 'web'
                cmd: install
          
          - name: Run yarn audit web directory
            uses: Borales/actions-yarn@v4.2.0
            with:
                dir: "web"
                cmd: audit

          - name: Web build
            working-directory: web
            env:
                CI: ""
            run: npm run build
              
          - name: Npm install infrastructure directory
            working-directory: infra
            run: npm install

          - name: Npm audit infrastructure directory
            working-directory: infra
            run: npm audit

          - name: Synthesize Cloudformation templates
            working-directory: infra
            run: |
                CDK_NAG_ENABLED=true
                export STACK_NAME=CfnNagTest
                export REGION=us-east-1
                npx cdk synth

          - name: Scan VAMS WAF Cloudformation template
            uses: stelligent/cfn_nag@master
            with:
                input_path: infra/cdk.out/vams-waf-CfnNagTest-us-east-1.template.json
          
          - name: Scan VAMS Cloudformation template
            uses: stelligent/cfn_nag@master
            with:
                input_path: infra/cdk.out/vams-CfnNagTest-us-east-1.template.json

          - name: run checks
            working-directory: backend
            run: make all


